# Generated by Django 3.2.9 on 2021-11-03 23:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0003_remove_teams_generic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puzzle_text', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleAnswerMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('possible_answers', models.JSONField(blank=True, null=True)),
                ('puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='arg_backend.puzzle')),
            ],
        ),
    ]
