# Generated by Django 3.2.9 on 2021-11-04 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0005_puzzle_mannual_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='mannual_id',
        ),
        migrations.CreateModel(
            name='PuzzleQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_puzzle', to='arg_backend.puzzle')),
                ('parent_puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_puzzle', to='arg_backend.puzzle')),
            ],
        ),
    ]
