# Generated by Django 3.2.9 on 2021-11-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0006_auto_20211104_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='completion_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
