# Generated by Django 3.2.9 on 2021-11-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0009_auto_20211109_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='current_hint',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
