# Generated by Django 3.2.9 on 2021-11-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0010_alter_teams_current_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlequeue',
            name='possible_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
