# Generated by Django 3.2.9 on 2021-11-09 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0011_puzzlequeue_possible_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzlequeue',
            name='possible_answers',
        ),
        migrations.DeleteModel(
            name='PuzzleAnswerMapping',
        ),
    ]
