# Generated by Django 3.2.9 on 2021-11-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0012_auto_20211109_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
