# Generated by Django 3.2.9 on 2021-11-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0014_auto_20211111_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_text',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
