# Generated by Django 3.2.9 on 2022-01-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0015_alter_puzzle_puzzle_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
