# Generated by Django 3.2.9 on 2022-01-29 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0016_puzzle_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_mapper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=600)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='puzzlequeue',
            options={'ordering': ['parent_puzzle']},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ['-score']},
        ),
    ]
