# Generated by Django 3.2.9 on 2022-01-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0017_auto_20220129_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='players',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
    ]
