# Generated by Django 3.2.9 on 2022-02-12 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0019_image_mapper_current_puzzle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_mapper',
            name='current_puzzle',
        ),
        migrations.AddField(
            model_name='image_mapper',
            name='puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arg_backend.puzzle'),
        ),
    ]
