# Generated by Django 3.2.9 on 2022-02-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0020_auto_20220212_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_mapper',
            name='half_password',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='image_mapper',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
