# Generated by Django 3.2.9 on 2022-02-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0021_auto_20220212_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_mapper',
            name='full_password',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
