# Generated by Django 3.2.9 on 2022-02-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0022_image_mapper_full_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_mapper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='image_mapper',
            name='unlock_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
