# Generated by Django 3.2.9 on 2022-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg_backend', '0023_auto_20220212_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='team_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
